---
cdn:
  name: web-community-cdn
libraries:
  byu-theme-components:
    source: github:byuweb/byu-theme-components
    configuration:
      type: 'web-component'
      basic_usage:
        head:
          meta:
          - name: viewport
            content: 'width=device-width, initial-scale=1.0'
          styles:
          - byu-theme-components.min.css
          scripts:
          - src: byu-theme-components.min.js
            async: true
        body: >
          <byu-header>
            <h1 slot="site-title">Your Site Title Here</h1>
          </byu-header>
          <div>
            Content Goes Here
          </div>
          <byu-footer></byu-footer>
      preload:
        byu-theme-components.min.css:
        - lib: shared-icons
          version: latest
          file: logos/monogram-white.svg
        - lib: theme-fonts
          version: latest
          file: ringside/fonts.css
        - lib: theme-fonts
          version: latest
          file: public-sans/fonts.css
        byu-theme-components.min.js:
        - ./components.min.js
        - lib: shared-icons
          version: latest
          file: logos/monogram-white.svg
        - lib: theme-fonts
          version: latest
          file: ringside/fonts.css
        - lib: theme-fonts
          version: latest
          file: public-sans/fonts.css
  byu-card:
    source: github:byuweb/byu-card
    configuration:
      type: 'web-component'
  byu-calendar-components:
    source: github:byuweb/byu-calendar-components
    configuration:
      type: 'web-component'

# deprecated in favor of byu-calendar-components -included only for backwards compatibility
  byu-calendar-row:
    source: github:byuweb/byu-calendar-row
    configuration:
      type: 'web-component'
      show_in_directory: false
      deprecated: 'Please use byu-calendar-components instead'

# deprecated in favor of byu-calendar-components -included only for backwards compatibility
  byu-calendar-tile:
    source: github:byuweb/byu-calendar-tile
    configuration:
      type: 'web-component'
      show_in_directory: false
      deprecated: 'Please use byu-calendar-components instead'

  web-component-polyfills:
    source: github:byuweb/web-component-polyfills
    configuration:
      type: 'javascript'
#    source: npm:@webcomponents/webcomponentsjs
#    configuration:
#      versions:
#        "^1.0.7":
#          resources:
#            - webcomponents-*.js*
#            # Copy full web component bundle for backward compatibility
#            - src: webcomponents-lite.js
#              rename:
#                - regex: webcomponents-lite.js
#                  to: web-component-polyfills.min.js
#                - regex: webcomponents-lite.js
#                  to: web-component-polyfills.js

  web-component-polyfills-v2:
    source: github:byuweb/web-component-polyfills-v2
    configuration:
      type: 'javascript'
  shared-icons:
    configuration:
      type: 'images'
      aliases:
        redirect: false
        cache:
          immutable: true
    source: github:byuweb/shared-icons
  byu-theme-style-helpers:
    source: github:byuweb/byu-theme-style-helpers
    configuration:
      type: 'stylesheet'
  byu-news-components:
    source: github:byuweb/byu-news-components
    configuration:
      type: 'web-component'
  byu-feature-card:
    source: github:byuweb/byu-feature-card-component
    configuration:
      type: 'web-component'
  byu-hero-banner:
    source: github:byuweb/byu-hero-banner
    configuration:
      type: 'web-component'
  byu-faculty-directory:
    source: github:byuweb/byu-faculty-directory
    configuration:
      type: 'web-component'
  theme-fonts:
    source: github:byuweb/hoefler-fonts
    configuration:
      type: 'font'
      aliases:
        redirect: false
        cache:
          immutable: true
  byu-random-content:
    source: github:byuweb/byu-random-content
    configuration:
      type: 'web-component'
  browser-oauth-implicit:
    source: github:byuweb/byu-browser-oauth-implicit
    configuration:
      type: 'javascript'
      prerelease: true
  byu-user-info-oauth:
    source: github:byuweb/byu-user-info-oauth
    configuration:
      type: 'javascript'
      prerelease: true
  byu-person-lookup:
    source: github:byuweb/byu-person-lookup
    configuration:
      type: 'javascript'
      prerelease: true
  font-metrics:
    source: github:byuweb/font-metrics-collector
  build-test-lib:
    source: github:ThatJoeMoore/byu-web-cdn-demo-lib
    build: circleci
  product-logos:
    source: github:byuweb/product-logos

infrastructure:
  environments:
    dev:
      settings:
        root-dns: dev.cdn.byu.edu
        account-stack-name: web-community-cdn-account
        certificate-arn: arn:aws:acm:us-east-1:398230616010:certificate/811c7982-75e1-4565-b81b-4a4dad3e6b85
    stg:
      settings:
        root-dns: beta.cdn.byu.edu
        account-stack-name: web-community-cdn-account
        certificate-arn: arn:something
    prod:
      settings:
        root-dns: cdn.byu.edu
        account-stack-name: web-community-cdn-account
        certificate-arn: arn:something

