---
cdn:
  name: web-community-cdn
libraries:
  2017-core-components:
    source: github:byuweb/byu-theme-components
  byu-theme-components:
    source: github:byuweb/byu-theme-components
  byu-card:
    source: github:byuweb/byu-card
  byu-calendar-components:
    source: github:byuweb/byu-calendar-components

# deprecated in favor of byu-calendar-components -included only for backwards compatibility
  byu-calendar-row:
    source: github:byuweb/byu-calendar-row

# deprecated in favor of byu-calendar-components -included only for backwards compatibility
  byu-calendar-tile:
    source: github:byuweb/byu-calendar-tile

  web-component-polyfills:
    source: github:byuweb/web-component-polyfills
#    source: npm:@webcomponents/webcomponentsjs
#    configuration:
#      versions:
#        "^1.0.7":
#          resources:
#            - webcomponents-*.js*
#            # Copy full web component bundle for backward compatibility
#            - src: webcomponents-lite.js
#              rename:
#                - regex: webcomponents-lite.js
#                  to: web-component-polyfills.min.js
#                - regex: webcomponents-lite.js
#                  to: web-component-polyfills.js
  shared-icons:
    source: github:byuweb/shared-icons
  byu-theme-style-helpers:
    source: github:byuweb/byu-theme-style-helpers
  byu-news-components:
    source: github:byuweb/byu-news-components
  byu-feature-card:
    source: github:byuweb/byu-feature-card-component
  byu-hero-banner:
    source: github:byuweb/byu-hero-banner
#  cdn-site:
#    source: github:byuweb/web-cdn-site
  byu-faculty-directory:
    source: github:byuweb/byu-faculty-directory
  theme-fonts:
    source: github:byuweb/hoefler-fonts
  byu-random-content:
    source: github:byuweb/byu-random-content
  browser-oauth-implicit:
    source: github:byuweb/byu-browser-oauth-implicit
  byu-user-info-oauth:
    source: github:byuweb/byu-user-info-oauth

infrastructure:
  environments:
    dev:
      settings:
        root-dns: dev.cdn.byu.edu
        account-stack-name: web-community-cdn-account
        certificate-arn: arn:aws:acm:us-east-1:398230616010:certificate/811c7982-75e1-4565-b81b-4a4dad3e6b85
    stg:
      settings:
        root-dns: beta.cdn.byu.edu
        account-stack-name: web-community-cdn-account
        certificate-arn: arn:something
    prod:
      settings:
        root-dns: cdn.byu.edu
        account-stack-name: web-community-cdn-account
        certificate-arn: arn:something

