---
demo-lib:
  source: github:ThatJoeMoore/byu-web-cdn-demo-lib
2017-core-components:
  source: github:byuweb/byu-theme-components
byu-theme-components:
  source: github:byuweb/byu-theme-components
byu-card:
  source: github:byuweb/byu-card
byu-calendar-row:
  source: github:byuweb/byu-calendar-row
byu-calendar-tile:
  source: github:byuweb/byu-calendar-tile
web-component-polyfills:
  source: github:byuweb/web-component-polyfills
shared-icons:
  source: github:byuweb/shared-icons
byu-theme-style-helpers:
  source: github:byuweb/byu-theme-style-helpers
byu-news-components:
  source: github:byuweb/byu-news-components
byu-feature-card:
  source: github:byuweb/byu-feature-card-component
byu-hero-banner:
  source: github:byuweb/byu-hero-banner
byu-faculty-directory:
  source: github:byuweb/byu-faculty-directory
